# Generated by Django 4.2.5 on 2023-09-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='choices',
            field=models.TextField(blank=True, help_text='Inserisci le scelte, separate da una virgola (es. Opzione 1, Opzione 2)', null=True),
        ),
    ]
